---
- name: OpenStax Hypothesis Deployment
  hosts: hypothesis 
  roles:
    - role: openstax.common
      tags: common
    - role: postgres
      tags: postgresql
    - role: nginx
      tags: nginx
    - role: rabbitmq
      tags: rabbitmq
    - role: wsgi-app
      tags: wsgi-app
    - role: openstax.nodejs
      tags: nodejs
    - role: elastic-search
      tags: elastic-search
