---
- name: OpenStax Hypothesis Deployment
  hosts: hypothesis
  pre_tasks:
    - import_tasks: tasks/get_server_rev.yml
      run_once: true
      tags: pre-flight
    - import_tasks: tasks/app_user.yml
  roles:
    - role: openstax.common
      tags:
        - common
    - role: openstax.nginx
      tags:
        - nginx
    - role: openstax.postgres
      tags:
        - postgres
    - role: openstax.rabbitmq
      tags:
        - rabbitmq
    - role: openstax.elasticsearch
      tags:
        - elasticsearch
    - role: openstax.hypothesis
      tags:
        - hypothesis-app
    - role: openstax.papertrail
      tags:
        - papertrail
