---
- name: OpenStax Hypothesis Deployment
  hosts: hypothesis 
  vars:
  roles:
    - role: openstax.common
      tags: common
    - role: openstax.nodejs
      tags: nodejs
    - role: openstax.postgresql
      postgres_users:
        h_admin:
          database: "{{ database.name }}"
          password: "{{ database.password }}"
          roles:
            - NOSUPERUSER
            - NOCREATEDB
            - NOCREATEROLE
      tags: postgres
    - role: nginx
      tags: nginx
    - role: openstax.hypothesis
      tags: hypothesis
