---
- name: OpenStax Hypothesis Deployment
  hosts: hypothesis 
  roles:
    - role: openstax.common
      tags: common
    - role: openstax.postgres
      tags: postgres
    - role: openstax.nginx
      tags: nginx
    - role: openstax.rabbitmq
      tags: rabbitmq
    - role: openstax.wsgi
      tags: wsgi
    - role: openstax.nodejs
      tags: nodejs
    - role: openstax.elasticsearch
      tags: elasticsearch
    - role: openstax.hypothesis
      tags: hypothesis-app
