- src: https://github.com/openstax/ansible-role-common.git
  version: master
  name: openstax.common
- src: https://github.com/openstax/ansible-role-postgres.git
  version: master
  name: openstax.postgresql
- src: https://github.com/openstax/ansible-role-hypothesis.git
  version: master
  name: openstax.hypothesis
- src: https://github.com/openstax/ansible-role-nodejs.git
  version: master
  name: openstax.nodejs

